version: '3.1'
services:
  mongo:
    image: mongo:5.0
    container_name: 'mongodb'
    # volumes:
    #   - database:/var/lib/postgresql/data
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "27017:27017"
    # environment:
    #   - POSTGRES_PASSWORD=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_DB=categorizer
    #   - POSTGRES_HOST_AUTH_METHOD=md5
    #   - POSTGRES_INITDB_ARGS=--auth-host=md5

  tddfirst:
    image: myimage:latest
    container_name: 'myapp'
    restart: on-failure
    ports:
      - 8081:8081
    depends_on:
      - mongo

volumes:
  database:
